apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: secret-santa-api
spec:
  selector:
    matchLabels:
      app: secret-santa-api
  replicas: 1
  template:
    metadata:
      labels:
        app: secret-santa-api
    spec:
      containers:
      - name: secret-santa-api
        image: mckp/secret-santa-api  # or just image: redis
        imagePullPolicy: Never
        env:
          - name: DB_USER
            value: admin
          - name: DB_PASS
            value: psltest
          - name: DB_HOST
            value: postgres.default
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: "secret_santa"
          - name: JWT_SIGNING_SECRET
            value: super secret value
        ports:
        - containerPort: 5000
        - containerPort: 9464