apiVersion: v1
kind: Service
metadata:
  name: secret-santa-api
spec:
  ports:
  - name: api
    port: 5000
    targetPort: 5000
  - name: metrics
    port: 9464
    targetPort: 9464
  selector:
    app: secret-santa-api
